### PR TITLE
add "issue" tempalates

### PR DESCRIPTION
**Pull request by zolotokrylin**

### CODE REVIEW

**Comment by zolotokrylin** [comment]
@VarinderClearpool pls review and if all is good, share the link with stakeholders (Rob, Varinder, marketing / community management team, etc.)

**Comment by VarinderClearpool** [comment]
@zolotokrylin what is the link tho? Where can i find it ?

**Comment by zolotokrylin** [comment]
@VarinderClearpool all good, are we happy here?

**Comment by markholdex** [comment]
tested in: https://github.com/clearpool-finance/community/issues/3

**Pull request merged**
